title: Developing BCMI for meditation
description: PhD thesis of Krisztián Hofstädter
theme: just-the-docs

url: https://phd.krishofstadter.com`

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
